// Field guide copy for metadata screening – matches train_metadata_model.py risk factors
// Risk weight from model: Tobacco 2, Alcohol 1, Betel 2, HPV 2, Hygiene 1, Lesions 2, Bleeding 2, Swallowing 2, Patches 2, Family 1

export const LANGUAGES = [
  { code: "en", label: "English" },
  { code: "hi", label: "हिन्दी" },
  { code: "kn", label: "ಕನ್ನಡ" },
  { code: "fr", label: "Français" },
  { code: "zh", label: "中文" },
  { code: "es", label: "Español" },
];

export const FIELD_IDS = [
  "tobacco",
  "alcohol",
  "betel",
  "hpv",
  "hygiene",
  "lesions",
  "bleeding",
  "swallowing",
  "patches",
  "family",
];

export const RISK_WEIGHTS = {
  tobacco: 2,
  alcohol: 1,
  betel: 2,
  hpv: 2,
  hygiene: 1,
  lesions: 2,
  bleeding: 2,
  swallowing: 2,
  patches: 2,
  family: 1,
};

export const fieldGuideContent = {
  en: {
    title: "Screening fields guide",
    subtitle: "What each field means and how to enter 0 or 1",
    languageLabel: "Language",
    zeroMeans: "0 = No",
    oneMeans: "1 = Yes",
    ageLabel: "Age (years)",
    ageDesc: "Patient's age in years. Older age can be associated with higher risk.",
    riskChartTitle: "Relative risk weight of each factor",
    backToForm: "Back to form",
    fields: {
      tobacco: {
        name: "Tobacco Use",
        desc: "Role: Primary carcinogen delivery system. Tobacco contains over 70 known carcinogens that directly mutate oral DNA and suppress local immunity.",
        zero: "No tobacco use history",
        one: "Yes – active or former user",
      },
      alcohol: {
        name: "Alcohol Consumption",
        desc: "Role: Synergistic solvent. Alcohol dehydrates the oral mucosa, making it more permeable to tobacco carcinogens and other toxins.",
        zero: "No/low alcohol consumption",
        one: "Yes – regular or heavy consumption",
      },
      betel: {
        name: "Betel Quid Use",
        desc: "Role: Mechanical & chemical irritant. Betel quid and areca nut cause sub-mucous fibrosis and direct chemical damage to oral cells.",
        zero: "No betel/paan use",
        one: "Yes – regular use of betel/paan",
      },
      hpv: {
        name: "HPV Infection",
        desc: "Role: Viral oncogenesis. Specifically HPV-16 can integrate into human DNA, disrupting tumor suppressor proteins (p53 and pRb).",
        zero: "No known HPV infection",
        one: "Yes – known/suspected HPV",
      },
      hygiene: {
        name: "Poor Oral Hygiene",
        desc: "Role: Chronic inflammatory catalyst. Accumulation of bacteria triggers persistent inflammatory responses that can promote cell mutation.",
        zero: "Excellent oral hygiene",
        one: "Yes – poor or neglected hygiene",
      },
      lesions: {
        name: "Oral Lesions",
        desc: "Role: Clinical indicator. Non-healing sores or ulcers (lasting >2 weeks) are often the first visible signs of oral malignancy.",
        zero: "No persistent lesions",
        one: "Yes – active oral lesions present",
      },
      bleeding: {
        name: "Unexplained Bleeding",
        desc: "Role: Vascular disruption. Malignant growth often invades blood vessels, causing spontaneous bleeding without trauma.",
        zero: "No unexplained bleeding",
        one: "Yes – frequent spontaneous bleeding",
      },
      swallowing: {
        name: "Difficulty Swallowing",
        desc: "Role: Structural obstruction. Tumor expansion in the throat or back of the mouth can physically impede the swallowing reflex (Dysphagia).",
        zero: "Normal swallowing reflex",
        one: "Yes – persistent difficulty swallowing",
      },
      patches: {
        name: "White or Red Patches in Mouth",
        desc: "Role: Pre-cancerous markers. Leukoplakia (white) and Erythroplakia (red) are high-risk indicators of dysplastic cellular changes.",
        zero: "No white or red patches",
        one: "Yes – suspicious patches detected",
      },
      family: {
        name: "Family History of Cancer",
        desc: "Role: Genetic predisposition. Inherited genetic variations may reduce the body's efficiency in repairing DNA damage in oral tissues.",
        zero: "No immediate family history",
        one: "Yes – family history of oral/neck cancer",
      },
    },
  },
  hi: {
    title: "स्क्रीनिंग फ़ील्ड गाइड",
    subtitle: "हर फ़ील्ड का मतलब और 0 या 1 कैसे डालें",
    languageLabel: "भाषा",
    zeroMeans: "0 = नहीं",
    oneMeans: "1 = हाँ",
    ageLabel: "उम्र (वर्ष)",
    ageDesc: "मरीज़ की उम्र (वर्ष में)। अधिक उम्र जोखिम से जुड़ सकती है।",
    riskChartTitle: "प्रत्येक कारक का सापेक्ष जोखिम भार",
    backToForm: "फॉर्म पर वापस",
    fields: {
      tobacco: {
        name: "तंबाकू उपयोग",
        desc: "सिगरेट, सिगार, चबाने वाला तंबाकू या धूम्ररहित तंबाकू का वर्तमान या पूर्व उपयोग।",
        zero: "तंबाकू नहीं",
        one: "हाँ – तंबाकू उपयोग करता/करता था",
      },
      alcohol: {
        name: "शराब का सेवन",
        desc: "नियमित या अधिक शराब (तंबाकू के साथ जोखिम बढ़ाता है)।",
        zero: "शराब नहीं या कम",
        one: "हाँ – नियमित/अधिक शराब",
      },
      betel: {
        name: "पान/सुपारी उपयोग",
        desc: "पान, सुपारी या पान मसाला का उपयोग (दक्षिण एशिया में आम)। मजबूत जोखिम कारक।",
        zero: "पान/सुपारी नहीं",
        one: "हाँ – पान या सुपारी लेता है",
      },
      hpv: {
        name: "HPV संक्रमण",
        desc: "मुंह के क्षेत्र में HPV (खासकर HPV-16) का ज्ञात या संदिग्ध संक्रमण।",
        zero: "HPV ज्ञात नहीं",
        one: "हाँ – ज्ञात या संदिग्ध HPV",
      },
      hygiene: {
        name: "खराब मौखिक स्वच्छता",
        desc: "अनियमित ब्रशिंग, फ्लॉस नहीं, अनुपचारित दांत या मसूड़े की बीमारी।",
        zero: "अच्छी स्वच्छता",
        one: "हाँ – खराब या उपेक्षित स्वच्छता",
      },
      lesions: {
        name: "मौखिक घाव",
        desc: "मुंह में दो सप्ताह से अधिक रहने वाला कोई भी न भरने वाला घाव या पैच।",
        zero: "ऐसे घाव नहीं",
        one: "हाँ – लगातार घाव या लेशन",
      },
      bleeding: {
        name: "बिना कारण रक्तस्राव",
        desc: "मुंह या मसूड़ों से बिना स्पष्ट कारण रक्तस्राव।",
        zero: "अस्पष्ट रक्तस्राव नहीं",
        one: "हाँ – मुंह में अस्पष्ट रक्तस्राव",
      },
      swallowing: {
        name: "निगलने में कठिनाई",
        desc: "खाना या तरल निगलने में परेशानी (डिस्फेजिया)।",
        zero: "निगलने में दिक्कत नहीं",
        one: "हाँ – निगलने में कठिनाई",
      },
      patches: {
        name: "मुंह में सफेद या लाल पैच",
        desc: "सफेद (ल्यूकोप्लाकिया) या लाल (एरिथ्रोप्लाकिया) पैच जो रगड़ने से नहीं हटते। प्री-कैंसर हो सकते हैं।",
        zero: "ऐसे पैच नहीं",
        one: "हाँ – सफेद या लाल पैच मौजूद",
      },
      family: {
        name: "कैंसर का पारिवारिक इतिहास",
        desc: "किसी भी कैंसर का करीबी परिवार (माता-पिता, भाई-बहन), खासकर सिर-गर्दन।",
        zero: "पारिवारिक इतिहास नहीं",
        one: "हाँ – परिवार में कैंसर का इतिहास",
      },
    },
  },
  es: {
    title: "Guía de campos del cuestionario",
    subtitle: "Qué significa cada campo y cómo indicar 0 o 1",
    languageLabel: "Idioma",
    zeroMeans: "0 = No",
    oneMeans: "1 = Sí",
    ageLabel: "Edad (años)",
    ageDesc: "Edad del paciente en años. La edad avanzada puede asociarse a mayor riesgo.",
    riskChartTitle: "Peso relativo de riesgo de cada factor",
    backToForm: "Volver al formulario",
    fields: {
      tobacco: {
        name: "Uso de tabaco",
        desc: "Cualquier uso actual o pasado de cigarrillos, puros, tabaco de mascar o sin humo.",
        zero: "No consume tabaco",
        one: "Sí – consume o ha consumido tabaco",
      },
      alcohol: {
        name: "Consumo de alcohol",
        desc: "Uso regular o excesivo de alcohol (aumenta el riesgo junto con el tabaco).",
        zero: "No o poco alcohol",
        one: "Sí – consumo regular o alto de alcohol",
      },
      betel: {
        name: "Uso de betel/areca",
        desc: "Uso de betel, paan o nuez de areca (común en partes de Asia). Factor de riesgo fuerte.",
        zero: "No usa betel/paan",
        one: "Sí – usa betel o paan",
      },
      hpv: {
        name: "Infección por HPV",
        desc: "Infección conocida o sospechada por virus del papiloma humano (sobre todo HPV-16) en zona oral.",
        zero: "No se conoce HPV",
        one: "Sí – HPV conocido o sospechado",
      },
      hygiene: {
        name: "Higiene oral deficiente",
        desc: "Cepillado irregular, sin hilo dental, caries sin tratar o enfermedad de encías crónica.",
        zero: "Buena higiene oral",
        one: "Sí – higiene oral pobre o descuidada",
      },
      lesions: {
        name: "Lesiones orales",
        desc: "Cualquier llaga, úlcera o parche anormal en la boca que dure más de dos semanas.",
        zero: "No hay esas lesiones",
        one: "Sí – llaga o lesión oral persistente",
      },
      bleeding: {
        name: "Sangrado sin causa aparente",
        desc: "Sangrado de boca o encías sin causa obvia (p. ej. traumatismo).",
        zero: "No hay sangrado inexplicable",
        one: "Sí – sangrado inexplicable en la boca",
      },
      swallowing: {
        name: "Dificultad para tragar",
        desc: "Problemas para tragar alimentos o líquidos (disfagia), frecuente en fases avanzadas.",
        zero: "No hay dificultad",
        one: "Sí – dificultad para tragar",
      },
      patches: {
        name: "Manchas blancas o rojas en la boca",
        desc: "Manchas blancas (leucoplasia) o rojas (eritroplasia) que no se quitan al frotar. Pueden ser precancerosas.",
        zero: "No hay esas manchas",
        one: "Sí – hay manchas blancas o rojas",
      },
      family: {
        name: "Antecedentes familiares de cáncer",
        desc: "Familiares cercanos (padre, madre, hermanos) con cualquier cáncer, sobre todo cabeza y cuello.",
        zero: "No hay antecedentes",
        one: "Sí – antecedentes familiares de cáncer",
      },
    },
  },
  kn: {
    title: "ಸ್ಕ್ರೀನಿಂಗ್ ಫೀಲ್ಡ್ ಗೈಡ್",
    subtitle: "ಪ್ರತಿ ಕ್ಷೇತ್ರವು ಏನು ಸೂಚಿಸುತ್ತದೆ ಮತ್ತು 0 ಅಥವಾ 1 ಅನ್ನು ಹೇಗೆ ನಮೂದಿಸಬೇಕು",
    languageLabel: "ಭಾಷೆ",
    zeroMeans: "0 = ಇಲ್ಲ",
    oneMeans: "1 = ಹೌದು",
    ageLabel: "ವಯಸ್ಸು (ವರ್ಷಗಳು)",
    ageDesc: "ರೋಗಿಯ ವಯಸ್ಸು. ಹೆಚ್ಚಿನ ವಯಸ್ಸು ಹೆಚ್ಚಿನ ಅಪಾಯದೊಂದಿಗೆ ಸಂಬಂಧ ಹೊಂದಿರಬಹುದು.",
    riskChartTitle: "ಪ್ರತಿ ಅಂಶದ ಸಾಪೇಕ್ಷ ಅಪಾಯದ ತೂಕ",
    backToForm: "ಫಾರ್ಮ್‌ಗೆ ಹಿಂತಿರುಗಿ",
    fields: {
      tobacco: {
        name: "ತಂಬಾಕು ಬಳಕೆ",
        desc: "ಪಾತ್ರ: ಪ್ರಾಥಮಿಕ ಕಾರ್ಸಿನೋಜೆನ್ ವಿತರಣಾ ವ್ಯವಸ್ಥೆ. ತಂಬಾಕು 70 ಕ್ಕೂ ಹೆಚ್ಚು ಕಾರ್ಸಿನೋಜೆನ್‌ಗಳನ್ನು ಹೊಂದಿದೆ.",
        zero: "ತಂಬಾಕು ಬಳಕೆಯ ಇತಿಹಾಸವಿಲ್ಲ",
        one: "ಹೌದು – ಸಕ್ರಿಯ ಅಥವಾ ಮಾಜಿ ಬಳಕೆದಾರ",
      },
      alcohol: {
        name: "ಮದ್ಯಪಾನ",
        desc: "ಪಾತ್ರ: ಸಿನರ್ಜಿಸ್ಟಿಕ್ ದ್ರಾವಕ. ಮದ್ಯವು ತಂಬಾಕಿನ ಪರಿಣಾಮವನ್ನು ಹೆಚ್ಚಿಸುತ್ತದೆ.",
        zero: "ಮದ್ಯಪಾನವಿಲ್ಲ",
        one: "ಹೌದು – ನಿಯಮಿತ ಅಥವಾ ಹೆಚ್ಚಿನ ಸೇವನೆ",
      },
      betel: {
        name: "ಬೀಡಾ/ಅಡಿಕೆ ಬಳಕೆ",
        desc: "ಪಾತ್ರ: ಯಾಂತ್ರಿಕ ಮತ್ತು ರಾಸಾಯನಿಕ ಕಿರಿಕಿರಿ. ಇದು ಬಾಯಿಯ ಜೀವಕೋಶಗಳಿಗೆ ಹಾನಿ ಮಾಡುತ್ತದೆ.",
        zero: "ಬೀಡಾ/ಪಾನ್ ಬಳಕೆ ಇಲ್ಲ",
        one: "ಹೌದು – ಬೀಡಾ/ಪಾನ್ ಬಳಕೆ ಇದೆ",
      },
      hpv: {
        name: "HPV ಸೋಂಕು",
        desc: "ಪಾತ್ರ: ವೈರಲ್ ಆಂಕೊಜೆನೆಸಿಸ್. ವಿಶೇಷವಾಗಿ HPV-16 ಜೀವಕೋಶಗಳ ಮೇಲೆ ಪರಿಣಾಮ ಬೀರಬಹುದು.",
        zero: "ತಿಳಿದಿರುವ HPV ಸೋಂಕು ಇಲ್ಲ",
        one: "ಹೌದು – ಶಂಕಿತ HPV ಸೋಂಕು",
      },
      hygiene: {
        name: "ಕಳಪೆ ಬಾಯಿ ನೈರ್ಮಲ್ಯ",
        desc: "ಪಾತ್ರ: ದೀರ್ಘಕಾಲದ ಉರಿಯೂತದ ವೇಗವರ್ಧಕ. ಬ್ಯಾಕ್ಟೀರಿಯಾಗಳು ಜೀವಕೋಶದ ಬದಲಾವಣೆಗೆ ಕಾರಣವಾಗಬಹುದು.",
        zero: "ಉತ್ತಮ ಬಾಯಿ ನೈರ್ಮಲ್ಯ",
        one: "ಹೌದು – ಕಳಪೆ ನೈರ್ಮಲ್ಯ",
      },
      lesions: {
        name: "ಬಾಯಿಯ ಹುಣ್ಣುಗಳು",
        desc: "ಪಾತ್ರ: ವೈದ್ಯಕೀಯ ಸೂಚಕ. 2 ವಾರಗಳಿಗಿಂತ ಹೆಚ್ಚು ಕಾಲ ಗುಣವಾಗದ ಹುಣ್ಣುಗಳು ಅಪಾಯಕಾರಿ.",
        zero: "ಹುಣ್ಣುಗಳು ಇಲ್ಲ",
        one: "ಹೌದು – ಬಾಯಿಯ ಹುಣ್ಣುಗಳು ಇವೆ",
      },
      bleeding: {
        name: "ವಿವರಿಸಲಾಗದ ರಕ್ತಸ್ರಾವ",
        desc: "ಪಾತ್ರ: ನಾಳೀಯ ಅಡ್ಡಿ. ಗಾಯವಿಲ್ಲದೆ ಬಾಯಿಯಲ್ಲಿ ರಕ್ತಸ್ರಾವವಾಗುವುದು.",
        zero: "ರಕ್ತಸ್ರಾವವಿಲ್ಲ",
        one: "ಹೌದು – ಆಗಾಗ್ಗೆ ರಕ್ತಸ್ರಾವ",
      },
      swallowing: {
        name: "ನುಂಗಲು ತೊಂದರೆ",
        desc: "ಪಾತ್ರ: ರಚನಾತ್ಮಕ ಅಡಚಣೆ. ಗಂಟಲಿನಲ್ಲಿ ಗೆಡ್ಡೆಯ ಬೆಳವಣಿಗೆಯಿಂದ ನುಂಗಲು ತೊಂದರೆಯಾಗಬಹುದು.",
        zero: "ಸಾಮಾನ್ಯ ನುಂಗುವಿಕೆ",
        one: "ಹೌದು – ನುಂಗಲು ತೊಂದರೆ ಇದೆ",
      },
      patches: {
        name: "ಬಾಯಿಯಲ್ಲಿ ಬಿಳಿ ಅಥವಾ ಕೆಂಪು ಕಲೆಗಳು",
        desc: "ಪಾತ್ರ: ಪೂರ್ವ ಕ್ಯಾನ್ಸರ್ ಗುರುತುಗಳು. ಲ್ಯುಕೋಪ್ಲಾಕಿಯಾ ಅಥವಾ ಎರಿಥ್ರೋಪ್ಲಾಕಿಯಾ.",
        zero: "ಯಾವುದೇ ಕಲೆಗಳಿಲ್ಲ",
        one: "ಹೌದು – ಅನುಮಾನಾಸ್ಪದ ಕಲೆಗಳಿವೆ",
      },
      family: {
        name: "ಕ್ಯಾನ್ಸರ್‌ನ ಕೌಟುಂಬಿಕ ಇತಿಹಾಸ",
        desc: "ಪಾತ್ರ: ಆನುವಂಶಿಕ ಪ್ರವೃತ್ತಿ. ಕುಟುಂಬದಲ್ಲಿ ಯಾರಿಗಾದರೂ ಕ್ಯಾನ್ಸರ್ ಇದ್ದರೆ ಅಪಾಯ ಹೆಚ್ಚು.",
        zero: "ಕೌಟುಂಬಿಕ ಇತಿಹಾಸವಿಲ್ಲ",
        one: "ಹೌದು – ಕುಟುಂಬದಲ್ಲಿ ಕ್ಯಾನ್ಸರ್ ಇತಿಹಾಸವಿದೆ",
      },
    },
  },
  fr: {
    title: "Guide des champs de dépistage",
    subtitle: "Signification de chaque champ et comment saisir 0 ou 1",
    languageLabel: "Langue",
    zeroMeans: "0 = Non",
    oneMeans: "1 = Oui",
    ageLabel: "Âge (années)",
    riskChartTitle: "Poids de risque relatif",
    backToForm: "Retour au formulaire",
    fields: {
      tobacco: { name: "Usage du Tabac", zero: "Aucun", one: "Oui" },
      alcohol: { name: "Consommation d'Alcool", zero: "Aucun", one: "Oui" },
      betel: { name: "Usage du Bétel", zero: "Aucun", one: "Oui" },
      hpv: { name: "Infection HPV", zero: "Aucun", one: "Oui" },
      hygiene: { name: "Mauvaise Hygiène", zero: "Bon", one: "Oui" },
      lesions: { name: "Lésions Orales", zero: "Aucun", one: "Oui" },
      bleeding: { name: "Saignements", zero: "Aucun", one: "Oui" },
      swallowing: { name: "Difficulté à Avaler", zero: "Aucun", one: "Oui" },
      patches: { name: "Taches Blanches/Rouges", zero: "Aucun", one: "Oui" },
      family: { name: "Antécédents Familiaux", zero: "Aucun", one: "Oui" },
    },
  },
  zh: {
    title: "筛查字段指南",
    subtitle: "每个字段的含义以及如何输入 0 或 1",
    languageLabel: "语言",
    zeroMeans: "0 = 否",
    oneMeans: "1 = 是",
    ageLabel: "年龄 (岁)",
    riskChartTitle: "相对风险权重",
    backToForm: "返回表单",
    fields: {
      tobacco: { name: "吸烟情况", zero: "否", one: "是" },
      alcohol: { name: "饮酒情况", zero: "否", one: "是" },
      betel: { name: "摈榔使用", zero: "否", one: "是" },
      hpv: { name: "HPV 感染", zero: "否", one: "是" },
      hygiene: { name: "口腔卫生", zero: "否", one: "是" },
      lesions: { name: "口腔病变", zero: "否", one: "是" },
      bleeding: { name: "不明原因出血", zero: "否", one: "是" },
      swallowing: { name: "吞咽困难", zero: "否", one: "是" },
      patches: { name: "红白斑块", zero: "否", one: "是" },
      family: { name: "癌症家族史", zero: "否", one: "是" },
    },
  },
};
